const HEROES=[
 {n:'Axe Guard',e:'🪓',c:1,a:['Warrior','Orc'],hp:760,atk:55},{n:'Tusk Brawler',e:'🐗',c:1,a:['Warrior','Beast'],hp:700,atk:60},{n:'Crystal Seer',e:'❄️',c:2,a:['Mage','Human'],hp:520,atk:70},{n:'Wind Ranger',e:'🏹',c:2,a:['Hunter','Elf'],hp:560,atk:78},{n:'Shadow Fiend',e:'🔥',c:3,a:['Demon','Warlock'],hp:650,atk:105},{n:'Tree Sage',e:'🌳',c:2,a:['Druid','Elf'],hp:820,atk:48},{n:'Kunk Captain',e:'⚓',c:4,a:['Warrior','Human'],hp:980,atk:95},{n:'Sniper Cub',e:'🎯',c:3,a:['Hunter','Dwarf'],hp:500,atk:120},{n:'Storm Sage',e:'⚡',c:4,a:['Mage','Spirit'],hp:620,atk:125},{n:'Venom Witch',e:'🐍',c:3,a:['Warlock','Beast'],hp:700,atk:82},{n:'Dragon Knight',e:'🐉',c:5,a:['Knight','Dragon'],hp:1150,atk:130},{n:'Moon Knight',e:'🌙',c:2,a:['Knight','Elf'],hp:760,atk:70}
];
const SYNERGY={Warrior:[2,'+160 team HP'],Mage:[2,'Enemies start weaker'],Hunter:[2,'Hunters +25 attack'],Knight:[2,'Knights gain armor'],Warlock:[2,'Team lifesteal'],Elf:[2,'Elves dodge'],Beast:[2,'Team +15 attack'],Human:[2,'Humans stun sometimes']};
let S={hp:100,gold:8,round:1,level:1,xp:0,shop:[],bench:[],board:Array(8).fill(null),selected:null,log:''};
const xpNeed=()=>S.level*2;
function uid(){return Math.random().toString(36).slice(2,9)}
function make(h){return {...h,id:uid(),star:1,maxhp:h.hp,hp:h.hp,atk:h.atk}}
function save(){localStorage.setItem('fac_mobile',JSON.stringify(S))}
function load(){let x=localStorage.getItem('fac_mobile'); if(x) S=JSON.parse(x); else roll(true)}
function roll(free=false){if(!free){if(S.gold<2)return msg('Not enough gold','Rolling costs 2 gold.');S.gold-=2}S.shop=Array.from({length:4},()=>HEROES[Math.floor(Math.random()*HEROES.length)]);render();save()}
function buy(i){let h=S.shop[i]; if(!h)return; if(S.gold<h.c)return msg('Not enough gold',`${h.n} costs ${h.c}.`); if(S.bench.length>=5)return msg('Bench full','Move or sell a unit first.'); S.gold-=h.c; S.bench.push(make(h)); S.shop[i]=null; combine(); render(); save()}
function combine(){for(const loc of ['bench','board']){let arr=loc==='bench'?S.bench:S.board.filter(Boolean); let groups={}; arr.forEach(u=>{let k=u.n+'|'+u.star;(groups[k]??=[]).push(u)}); for(let k in groups){if(groups[k].length>=3){let keep=groups[k][0]; keep.star++; keep.maxhp=Math.floor(keep.maxhp*1.8); keep.hp=keep.maxhp; keep.atk=Math.floor(keep.atk*1.7); let ids=groups[k].slice(1,3).map(x=>x.id); S.bench=S.bench.filter(x=>!ids.includes(x.id)); S.board=S.board.map(x=>x&&ids.includes(x.id)?null:x); }}}}
function cap(){return S.level}
function place(idx){let filled=S.board.filter(Boolean).length;if(S.selected?.type==='bench'){if(S.board[idx])return; if(filled>=cap())return msg('Level cap reached',`You can place ${cap()} unit(s). Buy XP to level up.`); S.board[idx]=S.bench.splice(S.selected.i,1)[0]; S.selected=null} else if(S.selected?.type==='board'){[S.board[idx],S.board[S.selected.i]]=[S.board[S.selected.i],S.board[idx]]; S.selected=null} render(); save()}
function select(type,i){S.selected={type,i}; render()}
function sell(type,i){let u=type==='bench'?S.bench[i]:S.board[i]; if(!u)return; S.gold+=Math.max(1,u.c+u.star-1); if(type==='bench')S.bench.splice(i,1); else S.board[i]=null; S.selected=null; render(); save()}
function buyXp(){if(S.gold<4)return msg('Not enough gold','XP costs 4 gold.'); S.gold-=4; S.xp+=4; while(S.xp>=xpNeed()&&S.level<8){S.xp-=xpNeed();S.level++} render(); save()}
function activeSyn(team=S.board.filter(Boolean)){let counts={};team.forEach(u=>u.a.forEach(a=>counts[a]=(counts[a]||0)+1));return counts}
function buffs(team){let counts=activeSyn(team), hp=0, atk=0; if((counts.Warrior||0)>=2)hp+=160;if((counts.Beast||0)>=2)atk+=15;if((counts.Hunter||0)>=2)team.filter(u=>u.a.includes('Hunter')).forEach(u=>u.atk+=25); return {hp,atk,counts}}
function enemy(){let pool=Array.from({length:Math.min(7,1+Math.floor(S.round/2))},()=>make(HEROES[Math.floor(Math.random()*HEROES.length)])); pool.forEach(u=>{u.maxhp=Math.floor(u.maxhp*(.75+S.round*.08));u.hp=u.maxhp;u.atk=Math.floor(u.atk*(.75+S.round*.06))});return pool.slice(0,Math.min(8,Math.ceil(S.round/2)+1))}
function fight(){let team=S.board.filter(Boolean).map(u=>({...u,hp:u.maxhp,atk:u.atk})); if(!team.length)return msg('No fighters','Place at least one unit on the board.'); let en=enemy(); let b=buffs(team); team.forEach(u=>{u.maxhp+=b.hp;u.hp=u.maxhp;u.atk+=b.atk}); let rounds=0; while(team.some(u=>u.hp>0)&&en.some(u=>u.hp>0)&&rounds<80){rounds++; for(let side of [team,en]){let foes=side===team?en:team; side.filter(u=>u.hp>0).forEach(u=>{let t=foes.filter(x=>x.hp>0)[0]; if(t)t.hp-=u.atk;});}}
 let win=team.some(u=>u.hp>0); if(win){let gain=5+Math.floor(S.round/3);S.gold+=gain;S.round++; msg('Victory!',`You won and gained ${gain} gold.`)} else {let dmg=5+Math.floor(S.round/2);S.hp-=dmg;S.gold+=3;S.round++; msg('Defeat',`You lost ${dmg} HP but gained 3 gold.`)} if(S.hp<=0){msg('Game over',`You survived to round ${S.round}. Press Reset to restart.`)} roll(true); render(); save()}
function unitHtml(u,loc,i){if(!u)return `<div class="slot empty" onclick="place(${i})"></div>`; let sel=S.selected&&S.selected.type===loc&&S.selected.i===i?' selected':'';return `<button class="unit${sel}" onclick="select('${loc}',${i})" ondblclick="sell('${loc}',${i})"><span class="stars">${'★'.repeat(u.star)}</span><div class="face">${u.e}</div><div class="name">${u.n}</div><div class="meta">${u.a.join(' · ')}</div><div class="hpbar"><div class="hpfill" style="width:${100*u.hp/u.maxhp}%"></div></div><span class="cost">${u.c}💰</span></button>`}
function render(){document.getElementById('hp').textContent=S.hp;document.getElementById('gold').textContent=S.gold;document.getElementById('round').textContent=S.round;document.getElementById('level').textContent=S.level;document.getElementById('xp').textContent=S.xp;document.getElementById('xpNeed').textContent=xpNeed();document.getElementById('cap').textContent=`${S.board.filter(Boolean).length}/${cap()}`;document.getElementById('board').innerHTML=S.board.map((u,i)=>unitHtml(u,'board',i)).join('');document.getElementById('bench').innerHTML=Array.from({length:5},(_,i)=>S.bench[i]?unitHtml(S.bench[i],'bench',i):'<div class="slot empty"></div>').join('');document.getElementById('shop').innerHTML=S.shop.map((h,i)=>h?`<button class="unit" onclick="buy(${i})"><div class="face">${h.e}</div><div class="name">${h.n}</div><div class="meta">${h.a.join(' · ')}</div><span class="cost">${h.c}💰</span></button>`:'<div class="slot"></div>').join('');let c=activeSyn();document.getElementById('synergyList').innerHTML=Object.keys(c).map(k=>`<span class="tag">${k} ${c[k]}${SYNERGY[k]&&c[k]>=SYNERGY[k][0]?' ✓':''}</span>`).join('')||'<span class="tag">No synergies yet</span>';document.getElementById('status').textContent=S.selected?'Tap a board slot, or double-tap selected unit to sell':'Buy units, tap bench unit, tap board to place';}
function msg(t,b){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').textContent=b;document.getElementById('modal').classList.remove('hidden')}
document.getElementById('rollBtn').onclick=()=>roll();document.getElementById('xpBtn').onclick=buyXp;document.getElementById('fightBtn').onclick=fight;document.getElementById('resetBtn').onclick=()=>{localStorage.removeItem('fac_mobile');S={hp:100,gold:8,round:1,level:1,xp:0,shop:[],bench:[],board:Array(8).fill(null),selected:null};roll(true)};document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.add('hidden');load();render();
